dist: trusty
sudo: required
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
stages:
  - build and publish
  - deploy
if: tag IS blank

jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - "build/libs/food-finder-backline-0.0.1-SNAPSHOT.jar"
        skip_cleanup: true
    - stage: deploy
      language: java
      script:
        - echo "Downloading allocations server $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/FoodFinderBackline/releases/download/$RELEASE_TAG/food-finder-backline-0.0.1-SNAPSHOT.jar
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
        organization: $CF_ORG
        space: development
